In [ ]:
def recommended_course(age,stream,interest):
  if stream=='Science':
    if interest=='High':
      return np.random.choice(['AI','Data Science'])
    elif interest=='Medium':
      return np.random.choice(['Python','AI'])
    else:
      return 'Python'
  elif stream=='Commerce':
    if interest=='High':
      return 'Economics'
    elif interest=='Medium':
      return 'Accounting'
    else:
      return 'Management'
  elif stream=='Arts':
    if interest=='High':
      return 'Sociology'
    elif interest=='medium':
      return 'History'
    else:
      return 'History'
  else:
    np.random.choice(courses)



In [ ]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,classification_report

In [ ]:
ages = [18, 19, 20, 21, 22, np.nan]
streams = ['Science', 'Commerce', 'Arts', None]
interest_levels = ['High', 'Medium', 'Low']
courses = ['Python', 'Accounting', 'Data Science', 'Sociology', 'Economics', 'History', 'AI', 'Management']


In [ ]:
data = {
    'Age': [np.random.choice(ages) for _ in range(1000)],
    'Stream': [np.random.choice(streams) for _ in range(1000)],
    'Interest_Level': [np.random.choice(interest_levels) for _ in range(1000)]
}



In [ ]:
df = pd.DataFrame(data)
df['Stream'] = df['Stream'].replace({None: np.nan})

In [ ]:
df.isnull().sum()

Age               157
Stream            250
Interest_Level      0
dtype: int64

In [ ]:
imputer = SimpleImputer(strategy='most_frequent')
df[['Age','Stream']] = imputer.fit_transform(df[['Age','Stream']])


In [ ]:
# mode_imputer = SimpleImputer(strategy='most_frequent')

In [ ]:
# df[['Stream']] = mode_imputer.fit_transform(df[['Stream']])

In [ ]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [ ]:
df.isnull().sum()

Age               0
Stream            0
Interest_Level    0
dtype: int64

In [ ]:
df.head()

Age    Stream Interest_Level
0  20.0  Commerce           High
1  18.0      Arts           High
2  18.0   Science         Medium
3  22.0   Science         Medium
4  18.0      Arts         Medium

In [ ]:
df['Recommend_Course']=df.apply(lambda x:recommended_course(x['Age'],x['Stream'],x['Interest_Level']),axis=1)
df.head(5)

Age    Stream Interest_Level Recommend_Course
0  20.0  Commerce           High        Economics
1  18.0      Arts           High        Sociology
2  18.0   Science         Medium               AI
3  22.0   Science         Medium               AI
4  18.0      Arts         Medium          History

In [ ]:
df.isnull().sum()

Age                 0
Stream              0
Interest_Level      0
Recommend_Course    0
dtype: int64

In [ ]:
le_stream=LabelEncoder()
le_interest=LabelEncoder()
le_course=LabelEncoder()


In [ ]:
df['Interest_Level'].head()

0      High
1      High
2    Medium
3    Medium
4    Medium
Name: Interest_Level, dtype: object

In [ ]:
le_interest.fit_transform(df['Interest_Level'])

array([0, 0, 2, 2, 2, 2, 1, 0, 0, 0, 0, 0, 1, 0, 2, 2, 1, 1, 1, 1, 1, 2,
       1, 0, 0, 2, 1, 2, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 0, 0, 2, 1, 1, 1,
       2, 0, 2, 2, 1, 0, 1, 1, 0, 0, 2, 2, 1, 1, 0, 2, 2, 1, 1, 0, 1, 2,
       0, 2, 2, 2, 0, 1, 0, 1, 1, 1, 2, 0, 0, 1, 1, 1, 1, 2, 1, 2, 2, 0,
       0, 0, 0, 1, 2, 1, 2, 1, 1, 1, 2, 0, 1, 0, 1, 1, 0, 2, 1, 0, 2, 0,
       1, 2, 1, 0, 1, 2, 1, 2, 2, 1, 0, 0, 1, 2, 0, 2, 2, 2, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 2, 0, 1, 2, 1, 2, 0, 2, 2, 1, 2, 1, 2, 1, 2, 2,
       1, 2, 2, 1, 1, 1, 2, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 2, 1, 2, 0, 0,
       0, 0, 2, 1, 0, 0, 2, 1, 2, 0, 1, 1, 0, 1, 1, 1, 2, 2, 0, 0, 1, 2,
       1, 0, 1, 1, 0, 2, 1, 1, 1, 1, 2, 1, 0, 2, 0, 2, 2, 0, 1, 0, 1, 0,
       1, 2, 2, 1, 0, 1, 2, 0, 1, 0, 2, 1, 0, 1, 1, 1, 1, 0, 2, 0, 2, 0,
       1, 1, 0, 2, 1, 0, 1, 2, 0, 1, 1, 0, 0, 2, 1, 2, 1, 2, 0, 0, 2, 1,
       2, 1, 1, 0, 1, 1, 2, 1, 0, 2, 0, 2, 0, 2, 2, 0, 1, 0, 2, 0, 1, 2,
       2, 1, 1, 0, 2, 1, 0, 2, 2, 2, 1, 2, 2, 0, 0,

In [ ]:
df['Stream_label']=le_stream.fit_transform(df['Stream'])
df['Interest_Level_label']=le_interest.fit_transform(df['Interest_Level'])
df['Recommend_Course_label']=le_course.fit_transform(df['Recommend_Course'])



In [ ]:
df['Stream'].unique()

array(['Commerce', 'Arts', 'Science'], dtype=object)

In [ ]:
# unique_values = [str(val) for val in df['Interest_Level'].unique()]
# print(unique_values)



In [ ]:
df.head()

Age    Stream Interest_Level Recommend_Course  Stream_label  \
0  20.0  Commerce           High        Economics             1   
1  18.0      Arts           High        Sociology             0   
2  18.0   Science         Medium               AI             2   
3  22.0   Science         Medium               AI             2   
4  18.0      Arts         Medium          History             0   

   Interest_Level_label  Recommend_Course_label  
0                     0                       3  
1                     0                       7  
2                     2                       0  
3                     2                       0  
4                     2                       4

In [ ]:
X=df[['Age','Stream_label','Interest_Level_label']]
y=df['Recommend_Course']

In [ ]:
df['Stream'].unique()

array(['Commerce', 'Arts', 'Science'], dtype=object)

In [ ]:
scaled=StandardScaler()
X_scaled=scaled.fit_transform(X)
X_scaled

array([[ 0.21377762,  0.30286549, -1.27809437],
       [-1.10583733, -0.88020283, -1.27809437],
       [-1.10583733,  1.48593381,  1.1916532 ],
       ...,
       [-1.10583733, -0.88020283, -0.04322058],
       [-1.10583733, -0.88020283,  1.1916532 ],
       [-1.10583733,  0.30286549, -1.27809437]])

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X_scaled,y,train_size=0.8,random_state=42)

In [ ]:
param_grid = {'n_neighbors': np.arange(1, 11)}
knn = KNeighborsClassifier()
grid = GridSearchCV(knn, param_grid,cv=3)
grid.fit(X_train, y_train)

best_k = grid.best_params_['n_neighbors']
print("🔍 Best K:", best_k)

🔍 Best K: 6


In [ ]:
knn_best=KNeighborsClassifier(n_neighbors=best_k)
knn_best.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=np.int64(6))

In [ ]:
y_pred=knn_best.predict(X_test)
y_pred

array(['History', 'Accounting', 'Sociology', np.str_('AI'), 'History',
       'Accounting', 'Management', 'Accounting', np.str_('AI'), 'History',
       'Accounting', 'Accounting', 'History', 'Accounting', 'Sociology',
       'History', np.str_('Python'), 'History', 'History', 'History',
       'History', 'Economics', 'History', np.str_('Python'), 'Sociology',
       'History', np.str_('Data Science'), 'Economics', 'Management',
       'Management', 'History', np.str_('AI'), 'History', 'History',
       'Sociology', 'History', np.str_('Python'), 'History', 'Sociology',
       'History', 'Accounting', 'History', np.str_('AI'), 'Economics',
       'Sociology', 'History', 'Management', 'History',
       np.str_('Data Science'), 'Management', np.str_('AI'),
       np.str_('Python'), np.str_('AI'), 'History', 'Sociology',
       'Sociology', 'History', np.str_('AI'), np.str_('AI'), 'History',
       'History', 'History', 'Sociology', 'History', np.str_('AI'),
       np.str_('Python'), np.st

In [ ]:
y_pred

array(['History', 'Accounting', 'Sociology', np.str_('AI'), 'History',
       'Accounting', 'Management', 'Accounting', np.str_('AI'), 'History',
       'Accounting', 'Accounting', 'History', 'Accounting', 'Sociology',
       'History', np.str_('Python'), 'History', 'History', 'History',
       'History', 'Economics', 'History', np.str_('Python'), 'Sociology',
       'History', np.str_('Data Science'), 'Economics', 'Management',
       'Management', 'History', np.str_('AI'), 'History', 'History',
       'Sociology', 'History', np.str_('Python'), 'History', 'Sociology',
       'History', 'Accounting', 'History', np.str_('AI'), 'Economics',
       'Sociology', 'History', 'Management', 'History',
       np.str_('Data Science'), 'Management', np.str_('AI'),
       np.str_('Python'), np.str_('AI'), 'History', 'Sociology',
       'Sociology', 'History', np.str_('AI'), np.str_('AI'), 'History',
       'History', 'History', 'Sociology', 'History', np.str_('AI'),
       np.str_('Python'), np.st

In [ ]:
accuracy_score(y_test,y_pred)

0.93

In [ ]:
print("✅ Accuracy:", accuracy_score(y_test, y_pred))

# print("📊 Classification Report:\n", classification_report(y_test, y_pred, labels=unique_labels, target_names=target_names))

# print("📊 Classification Report:\n", classification_report(y_test, y_pred, target_names=le_course.classes_))

✅ Accuracy: 0.93


In [ ]:
new_student=pd.DataFrame([[19,'Science','Low']],columns=['Age','Stream','Interest_Level'])
new_student

Age   Stream Interest_Level
0   19  Science            Low

In [ ]:
new_student['Stream']=le_stream.transform(new_student['Stream'])

In [ ]:
new_student

Age  Stream Interest_Level
0   19       2            Low

In [ ]:
le_interest

LabelEncoder()

In [ ]:
new_student['Interest_Level']=le_interest.transform(new_student['Interest_Level'])

In [ ]:
new_student

Age  Stream  Interest_Level
0   19       2               1

In [ ]:
new_student.rename(columns={
    'Interest_Level': 'Interest_Level_label',
    'Stream': 'Stream_label'
}, inplace=True)

In [ ]:
new_student

Age  Stream_label  Interest_Level_label
0   19             2                     1

In [ ]:
new_student_scaled=scaled.transform(new_student)
new_student_scaled

array([[-0.44602986,  1.48593381, -0.04322058]])

In [ ]:
predicted_label=knn_best.predict(new_student_scaled)
predicted_label[0]

np.str_('Python')

In [ ]:
# predicted_course=le_course.inverse_transform(predicted_label)
# predicted_course[0]